[FileDialog]
history=file:///home/dread-wing, file:///home/dread-wing/Downloads, file:///home/dread-wing/Downloads/[Exiled-Destiny] Neon Genesis Evangelion - The End Of Evangelion (Movie), file:///home/dread-wing/Downloads/Kaguya-sama Love is War 1080p BD Dual-Audio AV1-DBMS/Season 00, file:///home/dread-wing/Downloads/Kaguya-sama Love is War 1080p BD Dual-Audio AV1-DBMS/Season 01, file:///home/dread-wing/Downloads/Kaguya-sama Love is War 1080p BD Dual-Audio AV1-DBMS/Season 02
lastVisited=file:///home/dread-wing/Downloads/Kaguya-sama Love is War 1080p BD Dual-Audio AV1-DBMS/Season 02
qtVersion=5.15.19
shortcuts=file:, file:///home/dread-wing
sidebarWidth=95
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
